export default {
    js: "text/javascript; charset=utf-8",
    cjs: "text/javascript; charset=utf-8",
    mjs: "text/javascript; charset=utf-8",
    ts: "text/typescript; charset=utf-8",
    tsx: "text/typescript; charset=utf-8",
    jsx: "text/typescript; charset=utf-8",
    md: "text/markdown; charset=utf-8",
    txt: "text/plain; charset=utf-8",
    map: "text/plain; charset=utf-8",
    css: "text/css; charset=utf-8",
    xml: "text/xml; charset=utf-8",
    html: "text/html; charset=utf-8",
    json: "application/json; charset=utf-8",
    svg: "image/svg+xml; charset=utf-8",
    bmp: "image/bmp",
    gif: "image/gif",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    ico: "image/x-icon",
    png: "image/png",
    mp3: "audio/mpeg",
    mp4: "video/mp4",
    oga: "audio/ogg",
    ogv: "video/ogg",
    wav: "audio/x-wav",
    webp: "image/webp",
    webm: "video/webm",
    ogg: "application/ogg",
    pdf: "application/pdf",
    ttf: "application/x-font-ttf",
    woff: "application/x-font-woff",
    zip: "application/x-zip-compressed",
    rar: "application/x-rar-compressed",
    doc: "application/vnd.ms-word",
    xls: "application/vnd.ms-excel",
    wps: "application/vnd.ms-works",
    msg: "application/vnd.ms-outlook",
    ppt: "application/vnd.ms-powerpoint",
    exe: "application/vnd.microsoft.portable-executable",
    dll: "application/vnd.microsoft.portable-executable",
    docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    wasm: "application/wasm",
};
